### ISSUE TITLE
Highlight changed files

### ISSUE THREAD

**Issue by crepererum** [xfbs/diff.rs#1]
It would be helpful if the side bar could highlight files and directories that contain changes, so it's easier to find the needle in the haystack in large code bases.

Cool project idea BTW :sunglasses:

**Comment by xfbs** [comment]
Hey, thanks so much for the feedback! I'm working on implementing this right now. Basically going to make it so that it shows a quick summary of how many lines were added/removed. This is what it would look like:

![Screenshot from 2023-03-08 11-27-45](https://user-images.githubusercontent.com/786420/223688956-d5772ce8-d05f-494d-b33b-468868c84272.png)

This takes a little bit of rewriting (need to create all of the diff data ahead of time rather than lazily when viewing a file) but I think it should be doable.

**Comment by xfbs** [comment]
The latest commit implements this. Should already be deployed. Seems to work pretty good, only downside is that it now takes longer for the UI to load, because we have to generate the diff for all of the files in the crate (so that we can render the summary). I'm thinking of refactoring it a bit to where we initially only compute the diff for the current file, so that it can display something to the user, and meanwhile asynchronously compute the rest of the data and then backfill. So basically the summary data would appear a second or so later.
